# -*- coding: utf-8 -*-
"""Dashboard_Analitik_Big_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x6AbY8TXiFGwlvFD07wXG4BMJL8rBWLf
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

# Data
df = pd.read_csv("data_mahasiswa_final_bgt.csv")

st.title("Dashboard Analisis Jalur Masuk terhadap IPK dan Lama Studi Mahasiswa UIN SUSKA Program Studi Teknik Informatika")

# Rata-rata IPK per jalur masuk
st.subheader("Rata-rata IPK per Jalur Masuk")
ipk_mean = df.groupby("JALUR MASUK")["IPK"].mean().sort_values(ascending=False)
st.bar_chart(ipk_mean)

# Rata-rata Lama Studi per Jalur Masuk
st.subheader("Rata-rata Lama Studi per Jalur Masuk")
lama_mean = df.groupby("JALUR MASUK")["LAMA STUDI"].mean().sort_values()
st.bar_chart(lama_mean)

# Ubah String jadi numerik
le = LabelEncoder()
df["jalur_index"] = le.fit_transform(df["JALUR MASUK"])

# Korelasi visual: Jalur Index vs IPK
st.subheader("Korelasi Jalur Masuk terhadap IPK")
sns.regplot(x="jalur_index", y="IPK", data=df)
st.pyplot(plt.gcf())
plt.clf()

# Korelasi visual: Jalur Index vs Lama Studi
st.subheader("Korelasi Jalur Masuk terhadap Lama Studi")
sns.regplot(x="jalur_index", y="LAMA STUDI", data=df)
st.pyplot(plt.gcf())
plt.clf()

